AZURE_OPENAI_API_URL=https://hospital-ws-bot.openai.azure.com/openai/deployments/gpt-4o-hospital/chat/completions?api-version=2025-01-01-preview
AZURE_OPENAI_API_KEY=C97NzKU1SOTJvVdJGHOM6A5BO8kEtcg8gIYmMcF8N9bmM7i1LXBsJQQJ99BCACHYHv6XJ3w3AAABACOGroNg
AZURE_OPENAI_API_VERSION=2024-05-01-preview
FINE_TUNED_MODEL_NAME=gpt-4o-2024-08-06.ft-8bc2bf88eb78422caab0fd2dcc2279c9

